//------------------------------------------------------------------------------
<<<<<<< HEAD
// <自動產生的>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </自動產生的>
//------------------------------------------------------------------------------

namespace LongMeter
{


=======
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace LongMeter
{
>>>>>>> Ru
    public partial class SiteMaster
    {

        /// <summary>
<<<<<<< HEAD
=======
        /// HeadContent 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
>>>>>>> Ru
        /// MainContent 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
<<<<<<< HEAD
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
=======
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
>>>>>>> Ru
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
